<a href="https://colab.research.google.com/github/pras-4795/AIMLColab/blob/master/PrasanthParaselli_AI0051_assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DL Quiz

1) output is 75.0

In [0]:
import tensorflow as tf
a = tf.constant(10, dtype= 'float32') 
b = tf.Variable(a*2)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(b))

20.0


3)  A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operations and build our computation graph, without needing the data

4) W and b should be variables, x and y should be place holders since we need to feed data to x and y, W and b can be variables since they have to be initialized with constant values.

5) error is x is initialized with 2,4 array instead of 3,4 array

6) Shape of data is (32, 32, 3)

DL Test

In [0]:
import numpy as np

X = tf.placeholder("float", shape=(None,4,3))
NORMALIZED_MATRIX = (X - tf.math.reduce_mean(X))/(tf.math.reduce_std(X))

shape = tf.placeholder("float", None)
BATCHES_COMBINED_TENSOR = tf.reshape(X, [-1,3])

dimension = tf.placeholder("int32", None)
MATRIX_SUM = tf.reduce_sum(X, dimension)

SOFT_MAX = tf.nn.softmax(tf.reduce_sum(X, dimension))

MAX_VALUE_INDEX = tf.math.argmax(tf.nn.softmax(tf.reduce_sum(X, dimension)))

model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    data1 = np.random.randint(10, size=(4,3))
    data2 = np.random.randint(10, size=(4,3))
    data3 = np.random.randint(10, size=(4,3))
    data4 = np.random.randint(10, size=(4,3))
    print("--------------------------------------------------------------------------------------------------")
    print("Input Data")
    print("--------------------------------------------------------------------------------------------------")
    print(data1)
    print(data2)
    print(data3)
    print(data4)
    print("--------------------------------------------------------------------------------------------------")
    print("NORMALIZED_MATRIX")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(NORMALIZED_MATRIX, feed_dict = {X : [data1, data2, data3, data4] } ))
    print("--------------------------------------------------------------------------------------------------")
    print("BATCHES_COMBINED_TENSOR")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(BATCHES_COMBINED_TENSOR, feed_dict = {X : [data1, data2, data3, data4] } ))
    print("--------------------------------------------------------------------------------------------------")
    print("MATRIX SUM")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(MATRIX_SUM, feed_dict = {X : [data1, data2, data3, data4], dimension: [1,2]  } ))
    print("--------------------------------------------------------------------------------------------------")
    print("SOFT MAX")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(SOFT_MAX, feed_dict = {X : [data1, data2, data3, data4], dimension: [1,2]  } ))
    print("--------------------------------------------------------------------------------------------------")
    print("MAX_VALUE_INDEX")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(MAX_VALUE_INDEX, feed_dict = {X : [data1, data2, data3, data4], dimension: [1,2]  } ))
    print("--------------------------------------------------------------------------------------------------")
    
tf.reset_default_graph()



--------------------------------------------------------------------------------------------------
Input Data
--------------------------------------------------------------------------------------------------
[[3 9 9]
 [1 0 3]
 [4 0 9]
 [0 6 6]]
[[6 5 1]
 [8 6 8]
 [2 9 1]
 [2 0 1]]
[[8 9 8]
 [7 5 5]
 [0 0 0]
 [8 5 8]]
[[7 7 5]
 [6 9 2]
 [9 0 6]
 [9 4 9]]
--------------------------------------------------------------------------------------------------
NORMALIZED_MATRIX
--------------------------------------------------------------------------------------------------
[[[-0.5779555   1.2511781   1.2511781 ]
  [-1.1876668  -1.4925224  -0.5779555 ]
  [-0.27309987 -1.4925224   1.2511781 ]
  [-1.4925224   0.33661136  0.33661136]]

 [[ 0.33661136  0.03175575 -1.1876668 ]
  [ 0.94632256  0.33661136  0.94632256]
  [-0.8828111   1.2511781  -1.1876668 ]
  [-0.8828111  -1.4925224  -1.1876668 ]]

 [[ 0.94632256  1.2511781   0.94632256]
  [ 0.641467    0.03175575  0.03175575]
  [-1.4925224  -1.49252

In [0]:
rand = np.random.normal(0.5,0.3,4)

X = tf.constant([[2.0],[4.0]] , "float32")

W = tf.constant([[rand[0], rand[1]], [rand[2], rand[3]]])

b = tf.constant([[1.0],[1.0]])

f = tf.math.multiply(W,X) + b

model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    print(sess.run(f))


[[1.850733  2.4279406]
 [3.9727564 5.373809 ]]
