<a href="https://colab.research.google.com/github/pras-4795/AIMLColab/blob/master/PrasanthParaselli_AI0051_assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DL Quiz

1) output is 75.0

In [0]:
import tensorflow as tf
a = tf.constant(10, dtype= 'float32') 
b = tf.Variable(a*2)
model = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(model)
    print(sess.run(b))

20.0


3)  A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operations and build our computation graph, without needing the data

4) W and b should be variables, x and y should be place holders since we need to feed data to x and y, W and b can be variables since they have to be initialized with constant values.

5) error is x is initialized with 2,4 array instead of 3,4 array

6) Shape of data is (32, 32, 3)

DL Test

In [0]:
import numpy as np

X = tf.placeholder("float", shape=(None,4,3))
NORMALIZED_MATRIX = (X - tf.math.reduce_mean(X))/(tf.math.reduce_std(X))

shape = tf.placeholder("float", None)
BATCHES_COMBINED_TENSOR = tf.reshape(X, [-1,3])

dimension = tf.placeholder("int32", None)
MATRIX_SUM = tf.reduce_sum(X, dimension)

SOFT_MAX = tf.nn.softmax(tf.reduce_sum(X, dimension))

MAX_VALUE_INDEX = tf.math.argmax(tf.nn.softmax(tf.reduce_sum(X, dimension)))

model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    data1 = np.random.randint(10, size=(4,3))
    data2 = np.random.randint(10, size=(4,3))
    data3 = np.random.randint(10, size=(4,3))
    data4 = np.random.randint(10, size=(4,3))
    print("--------------------------------------------------------------------------------------------------")
    print("Input Data")
    print("--------------------------------------------------------------------------------------------------")
    print(data1)
    print(data2)
    print(data3)
    print(data4)
    print("--------------------------------------------------------------------------------------------------")
    print("NORMALIZED_MATRIX")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(NORMALIZED_MATRIX, feed_dict = {X : [data1, data2, data3, data4] } ))
    print("--------------------------------------------------------------------------------------------------")
    print("BATCHES_COMBINED_TENSOR")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(BATCHES_COMBINED_TENSOR, feed_dict = {X : [data1, data2, data3, data4] } ))
    print("--------------------------------------------------------------------------------------------------")
    print("MATRIX SUM")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(MATRIX_SUM, feed_dict = {X : [data1, data2, data3, data4], dimension: [1,2]  } ))
    print("--------------------------------------------------------------------------------------------------")
    print("SOFT MAX")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(SOFT_MAX, feed_dict = {X : [data1, data2, data3, data4], dimension: [1,2]  } ))
    print("--------------------------------------------------------------------------------------------------")
    print("MAX_VALUE_INDEX")
    print("--------------------------------------------------------------------------------------------------")
    print(sess.run(MAX_VALUE_INDEX, feed_dict = {X : [data1, data2, data3, data4], dimension: [1,2]  } ))
    print("--------------------------------------------------------------------------------------------------")
    
tf.reset_default_graph()



--------------------------------------------------------------------------------------------------
Input Data
--------------------------------------------------------------------------------------------------
[[1 4 0]
 [0 5 7]
 [9 2 8]
 [5 9 1]]
[[1 2 8]
 [4 3 1]
 [9 3 0]
 [2 7 3]]
[[0 4 9]
 [1 6 6]
 [8 6 3]
 [0 8 1]]
[[6 9 7]
 [5 0 4]
 [7 5 9]
 [8 9 6]]
--------------------------------------------------------------------------------------------------
NORMALIZED_MATRIX
--------------------------------------------------------------------------------------------------
[[[-1.1598728  -0.19442949 -1.4816872 ]
  [-1.4816872   0.12738493  0.77101374]
  [ 1.4146426  -0.83805835  1.0928282 ]
  [ 0.12738493  1.4146426  -1.1598728 ]]

 [[-1.1598728  -0.83805835  1.0928282 ]
  [-0.19442949 -0.51624393 -1.1598728 ]
  [ 1.4146426  -0.51624393 -1.4816872 ]
  [-0.83805835  0.77101374 -0.51624393]]

 [[-1.4816872  -0.19442949  1.4146426 ]
  [-1.1598728   0.44919935  0.44919935]
  [ 1.0928282   0.44919

In [0]:
rand = np.random.normal(0.5,0.3,4)

X = tf.constant([[2.0],[4.0]] , "float32")

W = tf.constant([[rand[0], rand[1]], [rand[2], rand[3]]])

b = tf.constant([[1.0],[1.0]])

f = tf.matmul(W,X) + b

g = (tf.math.exp(f) - tf.math.exp(-f))/(tf.math.exp(f) + tf.math.exp(-f)) + (1/(1+tf.math.exp(-f)))

model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    print("--------------------------------------------------------------------------------------------------")
    print("When X,W,b are constants")
    print("F Value")
    print(sess.run(f))
    print("--------------------------------------------------------------------------------------------------")
    print("( exp^(f) - exp^(-f) )/( exp^(f) + exp^(-f) ) + (1 / ( 1 + exp^(-f) )) value is:")
    print(sess.run(g))
    
tf.reset_default_graph()

--------------------------------------------------------------------------------------------------
When X,W,b are constants
F Value
[[3.9333248]
 [3.6269264]]
--------------------------------------------------------------------------------------------------
( exp^(f) - exp^(-f) )/( exp^(f) + exp^(-f) ) + (1 / ( 1 + exp^(-f) )) value is:
[[1.9800313]
 [1.9726775]]


In [0]:
rand = np.random.normal(0.5,0.3,4)

X = tf.placeholder("float", None)

W = tf.placeholder("float", None)

b = tf.placeholder("float", None)

f = tf.matmul(W,X) + b

g = (tf.math.exp(f) - tf.math.exp(-f))/(tf.math.exp(f) + tf.math.exp(-f)) + (1/(1+tf.math.exp(-f)))

model = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(model)
    print("--------------------------------------------------------------------------------------------------")
    print("When X,W,b are PlaceHolders")
    print("F Value")
    s = sess.run(f,feed_dict = {X : [[2.0],[4.0]], W: [[rand[0], rand[1]], [rand[2], rand[3]]], b: [[1.0],[1.0]] })
    print(s)
    print("--------------------------------------------------------------------------------------------------")
    print("( exp^(f) - exp^(-f) )/( exp^(f) + exp^(-f) ) + (1 / ( 1 + exp^(-f) )) value is:")
    print(sess.run(g, feed_dict = {f: s}))
    
tf.reset_default_graph()

--------------------------------------------------------------------------------------------------
When X,W,b are PlaceHolders
F Value
[[1.0702239]
 [3.2150116]]
--------------------------------------------------------------------------------------------------
( exp^(f) - exp^(-f) )/( exp^(f) + exp^(-f) ) + (1 / ( 1 + exp^(-f) )) value is:
[[1.5341849]
 [1.9581757]]


In 1st one all values as constants, In second one we used all placeholders and declared values during run time, we could have used variables for X, W, b instead of place holders in second one. But in first case, we should use X,W, b as constants only since the requirement is to have them as constants.

In [0]:
def mean_var(x):
  mean = tf.random.normal(shape=[x])
  var = tf.random.normal(shape=[x])
  return mean, var

